export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const INCREASE_ITEM_AMOUNT = 'INCREASE_AMOUNT';
export const SET_CART_AMOUNT = 'SET_CART_AMOUNT';
export const TOGGLE_CART = 'TOGGLE_CART';
export const DECREASE_ITEM_AMOUNT = 'DECREASE_ITEM_AMOUNT';
